# test_size: 0.2
# random_state: 5

GridSearchCV:
  estimator: sklearn.tree.DecisionTreeRegressor
  param_grid:
    max_depth: [15,16]
    criterion: [absolute_error]
    min_samples_split: [2,3,4]
    min_samples_leaf: [6,7,8]
    max_features: [12,13]
  cv: 5
  scoring: neg_mean_absolute_error