test_size: 0.2
random_state: 5

GridSearchCV:
  estimator: sklearn.tree.DecisionTreeRegressor
  param_grid:
    max_depth: [9]
    criterion: [absolute_error]
    min_samples_split: [4]
    min_samples_leaf: [5]
    max_features: [4]
  cv: 5
  scoring: neg_mean_absolute_error