# test_size: 0.2
# random_state: 5

GridSearchCV:
  estimator: sklearn.ensemble.GradientBoostingRegressor
  param_grid:
    max_depth : [15]
    n_estimators: [150]
    learning_rate: [0.1, 0.01, 0.001 ,0.2,0.7,0.8,0.9]
  cv: 5
  scoring: neg_mean_absolute_error