test_size: 0.2
random_state: 5

GridSearchCV:
  estimator: sklearn.ensemble.AdaBoostRegressor
  param_grid:
    n_estimators: [50,100,200]
    learning_rate: [0.1, 0.01, 0.001 ,0.2,0.7,0.8,0.9]
  cv: 5
  scoring: neg_mean_absolute_error